---
title:
header-includes:
 - \usepackage{bbm}
 - \usepackage{times}
 - \usepackage{setspace}
 - \usepackage{inputenc}
 - \onehalfspacing
 - \usepackage{lscape}
 - \usepackage{indentfirst}
 - \usepackage[brazil]{babel}
 - \usepackage{graphicx,psfrag}
 - \usepackage[T1]{fontenc}
 - \usepackage{times, amsmath, amsfonts, amssymb, amsthm}
 - \usepackage{xcolor}
 - \usepackage{url}
 - \usepackage[skip=2pt,size=normalsize]{caption}
 - \captionsetup{labelsep=endash, format=hang, width=\textwidth} 
 - \usepackage{placeins}
 - \usepackage[labelfont=bf]{caption}
 - \usepackage{sectsty}
 - \sectionfont{\fontsize{12}{15}\selectfont}
 - \subsectionfont{\fontsize{12}{15}\selectfont}
 - \usepackage{enumitem}
 - \usepackage{float}
 - \floatplacement{figure}{H}
 - \floatplacement{table}{H}
 - \usepackage{fancyhdr}
 - \pagestyle{fancy}
 - \lhead{}
 - \chead{}
 - \rhead{\thepage}
 - \lfoot{}
 - \cfoot{}
 - \rfoot{}
 - \renewcommand{\headrulewidth}{0pt}
 - \addto\captionsbrazil{\renewcommand{\contentsname}{}}
 - \addto\captionsbrazil{\renewcommand{\listfigurename}{}}
 - \addto\captionsbrazil{\renewcommand{\listtablename}{}}
 - \addto\captionsbrazil{\renewcommand{\bibname}{}}

output: pdf_document
keep_tex: true
fontsize: 12pt
geometry: "left = 2.5cm, right = 2cm, top = 2cm, bottom = 2cm"
setspace: nodisplayskipstretch
inputenc: utf8
bibliography: mybibfile.bib
endnote: no
csl: associacao-brasileira-de-normas-tecnicas.csl
---

```{=tex}
\newcommand{\universidade}{Universidade Federal de Pernambuco}
\newcommand{\centro}{Centro de Biociências}
\newcommand{\departamento}{Departamento de Zoologia}
\newcommand{\ppg}{Programa de Pós-Graduação em Biologia Animal}
\newcommand{\curso}{Ciências Biológicas com ênfase em Ciências Ambientais}
\newcommand{\titulo}{Curvas de acumulação de diversidade efetiva em comunidades de macrobentos da praia de tamandaré}
\newcommand{\nome}{Nome do Aluno}
\newcommand{\orientador}{Prof. Dr. Nome do Orientador }
\newcommand{\cidadeano}{Recife\\2022}
```
```{=tex}
\thispagestyle{empty}
\setstretch{1.0}
\begin{center}
{\MakeUppercase{\textbf{Universidade Federal de Pernambuco}}\\
  \MakeUppercase{\textbf{Centro de Biociências}}\\
  \MakeUppercase{\textbf{Ciências Biológicas com ênfase em Ciências Ambientais}}\\}
\end{center}
\vspace{3cm}
```
```{=tex}
\begin{center}
{\MakeUppercase{\textbf{Nome do Aluno}}}
\end{center}
\vspace{5cm}
```
```{=tex}
\begin{center}
\MakeUppercase{\textbf{Curvas de acumulação de diversidade efetiva em comunidades de macrobentos da praia de tamandaré}}
\end{center}
\vspace{5cm}
```
```{=tex}
\vspace{6cm}
\begin{center}
\MakeUppercase{\textbf{Recife\\2022}}
\end{center}
```
```{=tex}
\newpage
\thispagestyle{empty}
\setcounter{page}{1}
```
```{=tex}
\begin{center}
{\MakeUppercase{\textbf{Nome do Aluno}}}

\vspace{6cm}

\MakeUppercase{\textbf{Curvas de acumulação de diversidade efetiva em comunidades de macrobentos da praia de tamandaré}}


\vspace{3cm}
\end{center}
```
```{=tex}
\hspace{8cm}{\begin{minipage}{8.5cm}{
Trabalho de Conclusão de Curso apresentado a Coordenação do Curso de Graduação em Xxxxxx, da Universidade Federal de Pernambuco, como requisito parcial para obtenção do Título de Bacharel em Xxxxxxxx.\\

Orientador: \parbox[t]{6.0cm}{Prof. Dr. Nome do Orientador }}
\end{minipage}}
```
\vspace{6cm}

```{=tex}
\vspace{2.5cm}
\begin{center}
\MakeUppercase{\textbf{Recife\\2022}}
\end{center}
```
```{=tex}
\newpage
\thispagestyle{empty}
\begin{center}
\Large{\bf {FICHA CATALOGRÁFICA}}
\end{center}
```
```{=tex}
\newpage
\thispagestyle{empty}
```
```{=tex}
\begin{center}
{\MakeUppercase{\textbf{Nome do Aluno}}}

\vspace{3cm}

\MakeUppercase{\textbf{Curvas de acumulação de diversidade efetiva em comunidades de macrobentos da praia de tamandaré}}

\normalsize

\vspace{2cm}
\end{center}
```
```{=tex}
\hspace{8cm}{\begin{minipage}{8.5cm}{
Dissertação apresentada ao Programa de Pós-Graduação em Xxxxxxxx, Área de Concentração XXX, da Universidade Federal de Pernambuco, como requisito parcial para obtenção do título de Mestre em Xxxxxxxx.\\
Orientador: Prof. Dr. Nome do Orientador \\

Data de Aprovação: XX/XX/XX\\
Nota: X }

\vspace{1cm}

\end{minipage}}
```
\vspace{2.5cm}

```{=tex}
\begin{center}
{\Large{\textbf {Comissão Examinadora}}}

\vspace{1cm}

{\underline{\hspace{10cm}} \\}
{\bf Orientador Prof. Dr. Nome do Orientador \\}
{\bf Universidade Federal de Pernambuco}
\vspace{1cm}

{\underline{\hspace{10cm}} \\}
{\bf Prof. Dr. Componente da Banca\\}
{\bf Universidade Federal de Pernambuco}
\vspace{1cm}

{\underline{\hspace{10cm}} \\}
{\bf Prof. Dr. Componente da Banca\\}
{\bf Universidade Federal de Pernambuco}
\vspace{2cm}

\end{center}
```
```{=tex}
\newpage
\thispagestyle{empty}
```
```{r dedicatoria, child='01_Pre_textuais/dedicatoria.Rmd'}
```

```{=tex}
\newpage
\thispagestyle{empty}
```
```{r agradecimentos, child='01_Pre_textuais/agradecimentos.Rmd'}
```

```{=tex}
\newpage
\thispagestyle{empty}
```
```{r epigrafe, child='01_Pre_textuais/epigrafe.Rmd'}
```

```{=tex}
\newpage
\thispagestyle{empty}
```
```{r resumo, child='01_Pre_textuais/resumo.Rmd'}
```

```{=tex}
\newpage
\thispagestyle{empty}
```
```{r abstract, child='01_Pre_textuais/abstract.Rmd'}
```

\newpage

```{r abreviaturas, child = '01_Pre_textuais/abreviaturas.Rmd'}
```

```{=tex}
\newpage
\begin{center}
 \MakeUppercase{\bf{SUMÁRIO}}
\end{center}
\begin{center}
\tableofcontents
\end{center}
\thispagestyle{empty}
```
\newpage

```{r intro, child = '02_Textuais/introducao.Rmd'}
```

\newpage

```{r methods, child = '02_Textuais/metodos.Rmd'}
```

\newpage

```{r results, child = '02_Textuais/resultados.Rmd'}
```

\newpage

```{r discussion, child = '02_Textuais/discussao.Rmd'}
```

\newpage

```{r conclusion, child = '02_Textuais/conclusao.Rmd'}
```

\newpage

```{r biblio, child = '02_Textuais/bibliografia.Rmd'}
```

\newpage

```{r appendix, child = '02_Textuais/apendices.Rmd'}
```
